name = "arenastreams-api"
main = "api-worker.js"
compatibility_date = "2024-01-01"

[env.production]
name = "arenastreams-api"

[env.staging]
name = "arenastreams-api-staging"

# Environment variables
[vars]
STREAMED_API_BASE = "https://streamed.pk/api"
